/*
 * Author: Pattaraporn Potjanapimol
 * ID : 673040627-5
 * Sec : 2
 * The ConfigurableNumberGuessingGame Program
 * this program is a simple number guessing game where the user can define 
 * the range of numbers and the maximum number of attempts they are allowed.
 * user input Min Max Maximum number of tries
 * This program is randomly generated by method Math.random()
 * and the program checks for valid inputs by while Loop
 * Last-Update: 07/12/2567
 */
package potjanapimol.pattaraporn.lab3;

import java.util.Scanner;

public class ConfigurableNumberGuessingGame {
    public static void main(String[] args) {
        // user input
        Scanner input = new Scanner(System.in);
        System.out.print("Enter the min value:");
        int min = input.nextInt();
        // declare global variable
        int max = 0;
        int count = 0;
        // Check your input.Display Error messsage if max<min
        while (true) {
            System.out.print("Enter the max value:");
            max = input.nextInt();
            if (max >= min) {
                break; // Stop Loop
            }
            System.err.println("The max value must be at least equal to the min value");
        }
        // Check your input.Display Error messsage if count<=0
        while (true) {
            System.out.print("Enter the maximum number of tries:");
            count = input.nextInt();
            if (count > 0) {
                break; // Stop Loop
            }
            System.err.println("The maximum number of tries must be greater than 0");
        }
        int answer = min + (int) (Math.random() * (max - min) + 1); // generate answer
        System.out.println("Welcome to a number guessing game!");
        // if input is correct .value is change to false
        boolean check = true;
        // loop <your count> times
        for (int i = 1; i < count + 1; ++i) {
            int number = 0; // global variable in for loop
            while (true) {
                System.out.print("Enter an integer between " + min + " and " + max + ":");
                number = input.nextInt();
                // Check your input number.Display Error messsage if number is not between min
                // and max value
                if (number >= min && number <= max) {
                    break;
                }
                System.err.println("The number must be between 2 and 5");
            }

            // condition check your answer and number
            if (number == answer) {
                System.out.println("Congratulations!");
                if (i == 1) {
                    System.out.println("You have tried 1 time");
                } else {
                    System.out.println("You have tried " + i + " times");
                }
                check = false;
                break; // Stop the program
            } else if (number < answer) {
                System.out.println("Try a higher number!");
            } else {
                System.out.println("Try a lower number!");
            }
        }
        // if input is incorrect display text and correct answer
        if (check) {
            System.out.println("You have tried " + count + " times. You ran out of guesses\nThe answer is " + answer);
        }
        // close scanner
        input.close();
    }
}
