/*
 * Author: Pattaraporn Potjanapimol
 * ID : 673040627-5
 * Sec : 1
 * The NumberGuessingGam Program
 * This program is randomly generated by method Math.random()
 * user should be entered via the console using Scanner
 * you can input answer 5 times if the answer is incorrect
 * You will lost this game
 * Last-Update: 6/12/2567
 */
package potjanapimol.pattaraporn.lab3;

import java.util.Scanner;

public class NumberGuessingGame {
    public static void main(String[] args) {
        // user input
        Scanner input = new Scanner(System.in);
        int min = 1, max = 10; // declare variable
        int answer = min + (int) (Math.random() * (max - min) + 1); // generate answer
        System.out.println("Welcome to a number guessing game!");
        // if input is correct .value is change to false
        boolean check = true;
        // loop 5 times
        for (int i = 1; i < 6; ++i) {
            System.out.print("Enter an integer between " + min + " and " + max + ":"); // output
            int number = input.nextInt();
            // condition check your answer and number
            if (number == answer) {
                System.out.println("Congratulations!");
                if (i == 1) {
                    System.out.println("You have tried 1 time");
                } else {
                    System.out.println("You have tried " + i + " times");
                }
                check = false;
                break; // Stop the program
            } else if (number < answer) {
                System.out.println("Try a higher number!");
            } else {
                System.out.println("Try a lower number!");
            }
        }
        // if input is incorrect display text and correct answer
        if (check) {
            System.out.println("You have tried 5 times. You ran out of guesses\nThe answer is " + answer);
        }
        // close scanner
        input.close();
    }
}
